### ISSUE TITLE
Traceback : TypeError: can only concatenate str 

### ISSUE THREAD

**Issue by octavsly** [WKnak/fail2ban-block-ip-range#6] opened 2024-01-05 09:00 UTC
Maybe the following error report can be used...
```
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-block-ip-range.py", line 116, in <module>
    print("jail " + jail + " unsuccessful try to ban aggregated IP network: " + ip + " (result: " + result + ")")
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: can only concatenate str (not "CompletedProcess") to str
```

**Comment by pbiering** [comment] 2024-01-13 16:14
reproduced, will check for the issue

**Comment by pbiering** [comment] 2024-01-14 16:16
issue was introduced by https://github.com/WKnak/fail2ban-block-ip-range/pull/3/files

**Comment by WKnak** [comment] 2024-05-08 03:16
Due to some failed PR merges from my side, it is now fixed my PR #11 from @pbiering. Thanks!

**Closed as completed by WKnak** 2024-05-08 03:16 UTC
